# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    exclude: ^.devcontainer\S+.json|^.vscode\S+.json
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: check-ast
      - id: debug-statements
      - id: double-quote-string-fixer
      # - id: no-commit-to-branch
      #   args: [--branch, dev, --branch, master]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
    - id: autopep8
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.2
    hooks:
    -   id: pylint
        args: ["--score=n", "--disable=F0401"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-variables-names, flake8-bugbear]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    -   id: mypy
